//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reimburse
    {
        public Reimburse()
        {
            this.ReimburseDetails = new HashSet<ReimburseDetail>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> ClearanceDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> ActualPaid { get; set; }
    
        public virtual ICollection<ReimburseDetail> ReimburseDetails { get; set; }
    }
}
