//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReimburseDetail
    {
        public int Id { get; set; }
        public Nullable<int> ReimburseId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> ExpenseDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Reimburse Reimburse { get; set; }
    }
}
